# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dsvxtb.ui'
#
# Created: Thu Oct 31 09:49:09 2013
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dsvxtb(object):
    def setupUi(self, dsvxtb):
        dsvxtb.setObjectName(_fromUtf8("dsvxtb"))
        dsvxtb.resize(441, 463)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(dsvxtb.sizePolicy().hasHeightForWidth())
        dsvxtb.setSizePolicy(sizePolicy)
        dsvxtb.setMinimumSize(QtCore.QSize(4, 4))
        self.my_Run_OutputWindow = QtGui.QTextEdit(dsvxtb)
        self.my_Run_OutputWindow.setGeometry(QtCore.QRect(0, 0, 441, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.my_Run_OutputWindow.setFont(font)
        self.my_Run_OutputWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.my_Run_OutputWindow.setObjectName(_fromUtf8("my_Run_OutputWindow"))
        self.tabWidget = QtGui.QTabWidget(dsvxtb)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 160, 441, 341))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.my_COM_BAUD = QtGui.QComboBox(self.tab)
        self.my_COM_BAUD.setGeometry(QtCore.QRect(160, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_COM_BAUD.setFont(font)
        self.my_COM_BAUD.setObjectName(_fromUtf8("my_COM_BAUD"))
        self.my_Connect = QtGui.QCheckBox(self.tab)
        self.my_Connect.setGeometry(QtCore.QRect(270, 10, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Connect.setFont(font)
        self.my_Connect.setObjectName(_fromUtf8("my_Connect"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.my_Download = QtGui.QPushButton(self.tab)
        self.my_Download.setGeometry(QtCore.QRect(50, 180, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Download.setFont(font)
        self.my_Download.setObjectName(_fromUtf8("my_Download"))
        self.my_NSVX4 = QtGui.QLineEdit(self.tab)
        self.my_NSVX4.setGeometry(QtCore.QRect(150, 180, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_NSVX4.setFont(font)
        self.my_NSVX4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.my_NSVX4.setObjectName(_fromUtf8("my_NSVX4"))
        self.my_DAQ_Start = QtGui.QPushButton(self.tab)
        self.my_DAQ_Start.setGeometry(QtCore.QRect(50, 90, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_Start.setFont(font)
        self.my_DAQ_Start.setObjectName(_fromUtf8("my_DAQ_Start"))
        self.my_DAQ_NEvents = QtGui.QLineEdit(self.tab)
        self.my_DAQ_NEvents.setGeometry(QtCore.QRect(170, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_NEvents.setFont(font)
        self.my_DAQ_NEvents.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.my_DAQ_NEvents.setObjectName(_fromUtf8("my_DAQ_NEvents"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(150, 100, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(220, 100, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.my_DAQ_Simulate = QtGui.QCheckBox(self.tab)
        self.my_DAQ_Simulate.setEnabled(False)
        self.my_DAQ_Simulate.setGeometry(QtCore.QRect(270, 340, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_Simulate.setFont(font)
        self.my_DAQ_Simulate.setChecked(False)
        self.my_DAQ_Simulate.setObjectName(_fromUtf8("my_DAQ_Simulate"))
        self.my_DAQ_Writing = QtGui.QCheckBox(self.tab)
        self.my_DAQ_Writing.setEnabled(False)
        self.my_DAQ_Writing.setGeometry(QtCore.QRect(260, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_Writing.setFont(font)
        self.my_DAQ_Writing.setChecked(True)
        self.my_DAQ_Writing.setObjectName(_fromUtf8("my_DAQ_Writing"))
        self.my_DAQ_SelfTrig = QtGui.QCheckBox(self.tab)
        self.my_DAQ_SelfTrig.setEnabled(False)
        self.my_DAQ_SelfTrig.setGeometry(QtCore.QRect(270, 320, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_SelfTrig.setFont(font)
        self.my_DAQ_SelfTrig.setChecked(False)
        self.my_DAQ_SelfTrig.setObjectName(_fromUtf8("my_DAQ_SelfTrig"))
        self.my_Load_Sequencer = QtGui.QPushButton(self.tab)
        self.my_Load_Sequencer.setGeometry(QtCore.QRect(50, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Load_Sequencer.setFont(font)
        self.my_Load_Sequencer.setObjectName(_fromUtf8("my_Load_Sequencer"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(50, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.line_9 = QtGui.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(0, 170, 201, 20))
        font = QtGui.QFont()
        font.setKerning(True)
        self.line_9.setFont(font)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.my_Channel_Numbers = QtGui.QCheckBox(self.tab)
        self.my_Channel_Numbers.setGeometry(QtCore.QRect(270, 90, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Channel_Numbers.setFont(font)
        self.my_Channel_Numbers.setChecked(False)
        self.my_Channel_Numbers.setObjectName(_fromUtf8("my_Channel_Numbers"))
        self.my_DAQ_Interface = QtGui.QComboBox(self.tab)
        self.my_DAQ_Interface.setGeometry(QtCore.QRect(270, 30, 77, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_Interface.setFont(font)
        self.my_DAQ_Interface.setObjectName(_fromUtf8("my_DAQ_Interface"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(350, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.my_DAQ_Stop = QtGui.QPushButton(self.tab)
        self.my_DAQ_Stop.setGeometry(QtCore.QRect(50, 120, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_Stop.setFont(font)
        self.my_DAQ_Stop.setObjectName(_fromUtf8("my_DAQ_Stop"))
        self.my_DAQ_ExTrig = QtGui.QCheckBox(self.tab)
        self.my_DAQ_ExTrig.setEnabled(True)
        self.my_DAQ_ExTrig.setGeometry(QtCore.QRect(270, 130, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_ExTrig.setFont(font)
        self.my_DAQ_ExTrig.setChecked(False)
        self.my_DAQ_ExTrig.setObjectName(_fromUtf8("my_DAQ_ExTrig"))
        self.my_SlaveCSR = QtGui.QLineEdit(self.tab)
        self.my_SlaveCSR.setGeometry(QtCore.QRect(150, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_SlaveCSR.setFont(font)
        self.my_SlaveCSR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.my_SlaveCSR.setObjectName(_fromUtf8("my_SlaveCSR"))
        self.my_Slave_CSR = QtGui.QPushButton(self.tab)
        self.my_Slave_CSR.setGeometry(QtCore.QRect(50, 240, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Slave_CSR.setFont(font)
        self.my_Slave_CSR.setObjectName(_fromUtf8("my_Slave_CSR"))
        self.my_Slave_Reset = QtGui.QPushButton(self.tab)
        self.my_Slave_Reset.setGeometry(QtCore.QRect(0, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Slave_Reset.setFont(font)
        self.my_Slave_Reset.setObjectName(_fromUtf8("my_Slave_Reset"))
        self.my_Label_Switches = QtGui.QLabel(self.tab)
        self.my_Label_Switches.setGeometry(QtCore.QRect(330, 245, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Label_Switches.setFont(font)
        self.my_Label_Switches.setFrameShape(QtGui.QFrame.Box)
        self.my_Label_Switches.setText(_fromUtf8(""))
        self.my_Label_Switches.setMargin(0)
        self.my_Label_Switches.setObjectName(_fromUtf8("my_Label_Switches"))
        self.my_Label_Version = QtGui.QLabel(self.tab)
        self.my_Label_Version.setGeometry(QtCore.QRect(250, 245, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Label_Version.setFont(font)
        self.my_Label_Version.setFrameShape(QtGui.QFrame.Box)
        self.my_Label_Version.setText(_fromUtf8(""))
        self.my_Label_Version.setMargin(0)
        self.my_Label_Version.setObjectName(_fromUtf8("my_Label_Version"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(250, 230, 46, 13))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(335, 230, 81, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.my_COM = QtGui.QComboBox(self.tab)
        self.my_COM.setGeometry(QtCore.QRect(50, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_COM.setFont(font)
        self.my_COM.setObjectName(_fromUtf8("my_COM"))
        self.my_Calibration = QtGui.QCheckBox(self.tab)
        self.my_Calibration.setGeometry(QtCore.QRect(270, 110, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Calibration.setFont(font)
        self.my_Calibration.setChecked(False)
        self.my_Calibration.setObjectName(_fromUtf8("my_Calibration"))
        self.my_Retrigger = QtGui.QCheckBox(self.tab)
        self.my_Retrigger.setGeometry(QtCore.QRect(270, 160, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Retrigger.setFont(font)
        self.my_Retrigger.setChecked(False)
        self.my_Retrigger.setObjectName(_fromUtf8("my_Retrigger"))
        self.my_CN = QtGui.QLabel(self.tab)
        self.my_CN.setGeometry(QtCore.QRect(305, 245, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_CN.setFont(font)
        self.my_CN.setFrameShape(QtGui.QFrame.Box)
        self.my_CN.setText(_fromUtf8(""))
        self.my_CN.setMargin(0)
        self.my_CN.setObjectName(_fromUtf8("my_CN"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(300, 230, 31, 16))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.my_DAQ_Handshaking = QtGui.QCheckBox(self.tab)
        self.my_DAQ_Handshaking.setEnabled(False)
        self.my_DAQ_Handshaking.setGeometry(QtCore.QRect(130, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DAQ_Handshaking.setFont(font)
        self.my_DAQ_Handshaking.setToolTip(_fromUtf8(""))
        self.my_DAQ_Handshaking.setChecked(True)
        self.my_DAQ_Handshaking.setObjectName(_fromUtf8("my_DAQ_Handshaking"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.Debug = QtGui.QWidget()
        self.Debug.setObjectName(_fromUtf8("Debug"))
        self.line_3 = QtGui.QFrame(self.Debug)
        self.line_3.setGeometry(QtCore.QRect(170, 10, 20, 91))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_2 = QtGui.QFrame(self.Debug)
        self.line_2.setGeometry(QtCore.QRect(0, 10, 181, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(4, 4))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.my_Run_Command_Recording = QtGui.QCheckBox(self.Debug)
        self.my_Run_Command_Recording.setGeometry(QtCore.QRect(10, 50, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Command_Recording.setFont(font)
        self.my_Run_Command_Recording.setObjectName(_fromUtf8("my_Run_Command_Recording"))
        self.label_3 = QtGui.QLabel(self.Debug)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.my_Run_Exit = QtGui.QPushButton(self.Debug)
        self.my_Run_Exit.setGeometry(QtCore.QRect(350, 40, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.my_Run_Exit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Exit.setFont(font)
        self.my_Run_Exit.setObjectName(_fromUtf8("my_Run_Exit"))
        self.my_Run_Command_Repeat = QtGui.QPushButton(self.Debug)
        self.my_Run_Command_Repeat.setEnabled(False)
        self.my_Run_Command_Repeat.setGeometry(QtCore.QRect(10, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Command_Repeat.setFont(font)
        self.my_Run_Command_Repeat.setObjectName(_fromUtf8("my_Run_Command_Repeat"))
        self.my_Run_Delay = QtGui.QPushButton(self.Debug)
        self.my_Run_Delay.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Delay.setFont(font)
        self.my_Run_Delay.setObjectName(_fromUtf8("my_Run_Delay"))
        self.my_Run_Status = QtGui.QPushButton(self.Debug)
        self.my_Run_Status.setGeometry(QtCore.QRect(190, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Status.setFont(font)
        self.my_Run_Status.setObjectName(_fromUtf8("my_Run_Status"))
        self.label_4 = QtGui.QLabel(self.Debug)
        self.label_4.setGeometry(QtCore.QRect(130, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.my_Run_Stop = QtGui.QPushButton(self.Debug)
        self.my_Run_Stop.setGeometry(QtCore.QRect(280, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Stop.setFont(font)
        self.my_Run_Stop.setObjectName(_fromUtf8("my_Run_Stop"))
        self.my_Run_Delay_Txt = QtGui.QLineEdit(self.Debug)
        self.my_Run_Delay_Txt.setGeometry(QtCore.QRect(70, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Delay_Txt.setFont(font)
        self.my_Run_Delay_Txt.setObjectName(_fromUtf8("my_Run_Delay_Txt"))
        self.my_Run_Command_Repeat_NTimes = QtGui.QLineEdit(self.Debug)
        self.my_Run_Command_Repeat_NTimes.setGeometry(QtCore.QRect(70, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Command_Repeat_NTimes.setFont(font)
        self.my_Run_Command_Repeat_NTimes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.my_Run_Command_Repeat_NTimes.setObjectName(_fromUtf8("my_Run_Command_Repeat_NTimes"))
        self.label_2 = QtGui.QLabel(self.Debug)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.my_Run_Reg_Input = QtGui.QPushButton(self.Debug)
        self.my_Run_Reg_Input.setGeometry(QtCore.QRect(120, 150, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Input.setFont(font)
        self.my_Run_Reg_Input.setObjectName(_fromUtf8("my_Run_Reg_Input"))
        self.my_Run_Reg_Pulse = QtGui.QPushButton(self.Debug)
        self.my_Run_Reg_Pulse.setGeometry(QtCore.QRect(330, 150, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Pulse.setFont(font)
        self.my_Run_Reg_Pulse.setObjectName(_fromUtf8("my_Run_Reg_Pulse"))
        self.my_Run_Command = QtGui.QPushButton(self.Debug)
        self.my_Run_Command.setGeometry(QtCore.QRect(0, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Command.setFont(font)
        self.my_Run_Command.setObjectName(_fromUtf8("my_Run_Command"))
        self.my_Run_Reg_Clear = QtGui.QPushButton(self.Debug)
        self.my_Run_Reg_Clear.setGeometry(QtCore.QRect(330, 130, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Clear.setFont(font)
        self.my_Run_Reg_Clear.setObjectName(_fromUtf8("my_Run_Reg_Clear"))
        self.my_Run_Command_Txt = QtGui.QLineEdit(self.Debug)
        self.my_Run_Command_Txt.setGeometry(QtCore.QRect(90, 180, 311, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Command_Txt.setFont(font)
        self.my_Run_Command_Txt.setObjectName(_fromUtf8("my_Run_Command_Txt"))
        self.my_Run_Reg_Read = QtGui.QPushButton(self.Debug)
        self.my_Run_Reg_Read.setGeometry(QtCore.QRect(120, 130, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Read.setFont(font)
        self.my_Run_Reg_Read.setObjectName(_fromUtf8("my_Run_Reg_Read"))
        self.my_Run_Reg_Set = QtGui.QPushButton(self.Debug)
        self.my_Run_Reg_Set.setGeometry(QtCore.QRect(280, 130, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Set.setFont(font)
        self.my_Run_Reg_Set.setObjectName(_fromUtf8("my_Run_Reg_Set"))
        self.my_Run_Reg_Add = QtGui.QPushButton(self.Debug)
        self.my_Run_Reg_Add.setGeometry(QtCore.QRect(280, 150, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Add.setFont(font)
        self.my_Run_Reg_Add.setObjectName(_fromUtf8("my_Run_Reg_Add"))
        self.my_Run_Reg_Value = QtGui.QLineEdit(self.Debug)
        self.my_Run_Reg_Value.setGeometry(QtCore.QRect(170, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg_Value.setFont(font)
        self.my_Run_Reg_Value.setAutoFillBackground(False)
        self.my_Run_Reg_Value.setObjectName(_fromUtf8("my_Run_Reg_Value"))
        self.line = QtGui.QFrame(self.Debug)
        self.line.setGeometry(QtCore.QRect(0, 110, 431, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.Debug)
        self.label.setGeometry(QtCore.QRect(0, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.my_Run_Reg = QtGui.QSpinBox(self.Debug)
        self.my_Run_Reg.setGeometry(QtCore.QRect(40, 130, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Reg.setFont(font)
        self.my_Run_Reg.setMaximum(256)
        self.my_Run_Reg.setProperty("value", 0)
        self.my_Run_Reg.setObjectName(_fromUtf8("my_Run_Reg"))
        self.line_5 = QtGui.QFrame(self.Debug)
        self.line_5.setGeometry(QtCore.QRect(200, 230, 20, 41))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.my_Dbg_Verbosity = QtGui.QPushButton(self.Debug)
        self.my_Dbg_Verbosity.setGeometry(QtCore.QRect(230, 220, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Dbg_Verbosity.setFont(font)
        self.my_Dbg_Verbosity.setObjectName(_fromUtf8("my_Dbg_Verbosity"))
        self.my_Run_Chipskop_Arm = QtGui.QPushButton(self.Debug)
        self.my_Run_Chipskop_Arm.setGeometry(QtCore.QRect(120, 230, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Chipskop_Arm.setFont(font)
        self.my_Run_Chipskop_Arm.setObjectName(_fromUtf8("my_Run_Chipskop_Arm"))
        self.line_4 = QtGui.QFrame(self.Debug)
        self.line_4.setGeometry(QtCore.QRect(0, 220, 221, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.my_Run_Chipskop = QtGui.QPushButton(self.Debug)
        self.my_Run_Chipskop.setEnabled(False)
        self.my_Run_Chipskop.setGeometry(QtCore.QRect(10, 230, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.my_Run_Chipskop.setFont(font)
        self.my_Run_Chipskop.setObjectName(_fromUtf8("my_Run_Chipskop"))
        self.my_Run_Chipskop_Trig = QtGui.QPushButton(self.Debug)
        self.my_Run_Chipskop_Trig.setGeometry(QtCore.QRect(170, 230, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_Chipskop_Trig.setFont(font)
        self.my_Run_Chipskop_Trig.setObjectName(_fromUtf8("my_Run_Chipskop_Trig"))
        self.my_Dbg_Verbosity_Txt = QtGui.QLineEdit(self.Debug)
        self.my_Dbg_Verbosity_Txt.setGeometry(QtCore.QRect(320, 220, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.my_Dbg_Verbosity_Txt.setFont(font)
        self.my_Dbg_Verbosity_Txt.setObjectName(_fromUtf8("my_Dbg_Verbosity_Txt"))
        self.my_Run_EFROM = QtGui.QPushButton(self.Debug)
        self.my_Run_EFROM.setGeometry(QtCore.QRect(250, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Run_EFROM.setFont(font)
        self.my_Run_EFROM.setObjectName(_fromUtf8("my_Run_EFROM"))
        self.line_6 = QtGui.QFrame(self.Debug)
        self.line_6.setGeometry(QtCore.QRect(10, 260, 211, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.my_CTest = QtGui.QPushButton(self.Debug)
        self.my_CTest.setEnabled(False)
        self.my_CTest.setGeometry(QtCore.QRect(280, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_CTest.setFont(font)
        self.my_CTest.setObjectName(_fromUtf8("my_CTest"))
        self.line_7 = QtGui.QFrame(self.Debug)
        self.line_7.setGeometry(QtCore.QRect(0, 170, 391, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_5 = QtGui.QLabel(self.Debug)
        self.label_5.setGeometry(QtCore.QRect(110, 110, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_8 = QtGui.QFrame(self.Debug)
        self.line_8.setGeometry(QtCore.QRect(218, 125, 20, 16))
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.my_Help = QtGui.QPushButton(self.Debug)
        self.my_Help.setGeometry(QtCore.QRect(350, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Help.setFont(font)
        self.my_Help.setObjectName(_fromUtf8("my_Help"))
        self.my_Reset = QtGui.QPushButton(self.Debug)
        self.my_Reset.setGeometry(QtCore.QRect(280, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_Reset.setFont(font)
        self.my_Reset.setObjectName(_fromUtf8("my_Reset"))
        self.my_DumpFIFO = QtGui.QPushButton(self.Debug)
        self.my_DumpFIFO.setEnabled(False)
        self.my_DumpFIFO.setGeometry(QtCore.QRect(350, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_DumpFIFO.setFont(font)
        self.my_DumpFIFO.setObjectName(_fromUtf8("my_DumpFIFO"))
        self.my_STest = QtGui.QPushButton(self.Debug)
        self.my_STest.setEnabled(False)
        self.my_STest.setGeometry(QtCore.QRect(190, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_STest.setFont(font)
        self.my_STest.setObjectName(_fromUtf8("my_STest"))
        self.tabWidget.addTab(self.Debug, _fromUtf8(""))

        self.retranslateUi(dsvxtb)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dsvxtb)

    def retranslateUi(self, dsvxtb):
        dsvxtb.setWindowTitle(QtGui.QApplication.translate("dsvxtb", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.my_COM_BAUD.setToolTip(QtGui.QApplication.translate("dsvxtb", "Baud rate, Standard:460800", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Connect.setToolTip(QtGui.QApplication.translate("dsvxtb", "Connect to serial port", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Connect.setText(QtGui.QApplication.translate("dsvxtb", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("dsvxtb", "Slave number on the APB bus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dsvxtb", "UART:", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Download.setToolTip(QtGui.QApplication.translate("dsvxtb", "Download SVX4 chain using file fem.fem", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Download.setText(QtGui.QApplication.translate("dsvxtb", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.my_NSVX4.setToolTip(QtGui.QApplication.translate("dsvxtb", "Number of SVX4s in chain", None, QtGui.QApplication.UnicodeUTF8))
        self.my_NSVX4.setText(QtGui.QApplication.translate("dsvxtb", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Start.setToolTip(QtGui.QApplication.translate("dsvxtb", "Download SVX4 chain using file fem.fem", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Start.setText(QtGui.QApplication.translate("dsvxtb", "Start DAQ", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_NEvents.setToolTip(QtGui.QApplication.translate("dsvxtb", "Number of events to accept", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_NEvents.setText(QtGui.QApplication.translate("dsvxtb", "1e3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dsvxtb", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dsvxtb", "events", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Simulate.setToolTip(QtGui.QApplication.translate("dsvxtb", "Turn on event simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Simulate.setText(QtGui.QApplication.translate("dsvxtb", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Writing.setToolTip(QtGui.QApplication.translate("dsvxtb", "Enable writing to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Writing.setText(QtGui.QApplication.translate("dsvxtb", "Write to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_SelfTrig.setToolTip(QtGui.QApplication.translate("dsvxtb", "Re-trigger after each event", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_SelfTrig.setText(QtGui.QApplication.translate("dsvxtb", "Self trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Load_Sequencer.setToolTip(QtGui.QApplication.translate("dsvxtb", "Load sequencer file.\n"
"Depending on setting of External trigger the file is sqn_trig_external.txt of sqn_trig_internal.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Load_Sequencer.setText(QtGui.QApplication.translate("dsvxtb", "Load Sequencer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("dsvxtb", "Initialization", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Channel_Numbers.setToolTip(QtGui.QApplication.translate("dsvxtb", "If selected, then channel numers will be sent out, otherwise - ADC values", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Channel_Numbers.setText(QtGui.QApplication.translate("dsvxtb", "Channel Numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Interface.setToolTip(QtGui.QApplication.translate("dsvxtb", "DAQ destination interface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("dsvxtb", "Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Stop.setToolTip(QtGui.QApplication.translate("dsvxtb", "Download SVX4 chain using file fem.fem", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Stop.setText(QtGui.QApplication.translate("dsvxtb", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_ExTrig.setToolTip(QtGui.QApplication.translate("dsvxtb", "Enable external trigger, the seqencer will be changed to sqn_trig_external", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_ExTrig.setText(QtGui.QApplication.translate("dsvxtb", "External trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.my_SlaveCSR.setToolTip(QtGui.QApplication.translate("dsvxtb", "Confiuration value. \n"
"Bits [5:0] refer to switches to be closed, \n"
"Bit [6]: 0 for sending ADC values, 1 - for channel numbers ", None, QtGui.QApplication.UnicodeUTF8))
        self.my_SlaveCSR.setText(QtGui.QApplication.translate("dsvxtb", "0x1F", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Slave_CSR.setToolTip(QtGui.QApplication.translate("dsvxtb", "Configure slave board on the cable", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Slave_CSR.setText(QtGui.QApplication.translate("dsvxtb", "Slave CSR", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Slave_Reset.setToolTip(QtGui.QApplication.translate("dsvxtb", "Reset slave boards on the cable", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Slave_Reset.setText(QtGui.QApplication.translate("dsvxtb", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Label_Switches.setToolTip(QtGui.QApplication.translate("dsvxtb", "Status of switches [6:1]", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Label_Version.setToolTip(QtGui.QApplication.translate("dsvxtb", "Firmware version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("dsvxtb", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("dsvxtb", "Switches", None, QtGui.QApplication.UnicodeUTF8))
        self.my_COM.setToolTip(QtGui.QApplication.translate("dsvxtb", "Available ports", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Calibration.setToolTip(QtGui.QApplication.translate("dsvxtb", "Calibration data. The sequenser file will be changed. ", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Calibration.setText(QtGui.QApplication.translate("dsvxtb", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Retrigger.setToolTip(QtGui.QApplication.translate("dsvxtb", "Test mode of data taking using RS232. ", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Retrigger.setText(QtGui.QApplication.translate("dsvxtb", "Retrigger", None, QtGui.QApplication.UnicodeUTF8))
        self.my_CN.setToolTip(QtGui.QApplication.translate("dsvxtb", "Channels Numbers mode on Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("dsvxtb", "CN", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DAQ_Handshaking.setText(QtGui.QApplication.translate("dsvxtb", "HandShaking", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("dsvxtb", "Work", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Recording.setToolTip(QtGui.QApplication.translate("dsvxtb", "Start command recording", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Recording.setText(QtGui.QApplication.translate("dsvxtb", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dsvxtb", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Exit.setToolTip(QtGui.QApplication.translate("dsvxtb", "Safe exit of the control session by closing all connections.\n"
"The FEM is not affected and will continue running.", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Exit.setText(QtGui.QApplication.translate("dsvxtb", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Repeat.setToolTip(QtGui.QApplication.translate("dsvxtb", "Execute recorded commands", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Repeat.setText(QtGui.QApplication.translate("dsvxtb", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Delay.setText(QtGui.QApplication.translate("dsvxtb", "Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Status.setToolTip(QtGui.QApplication.translate("dsvxtb", "Status registers.", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Status.setText(QtGui.QApplication.translate("dsvxtb", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dsvxtb", "times", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Stop.setToolTip(QtGui.QApplication.translate("dsvxtb", "Stop the repeating thread by sending \'xx\' command", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Stop.setText(QtGui.QApplication.translate("dsvxtb", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Delay_Txt.setText(QtGui.QApplication.translate("dsvxtb", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Repeat_NTimes.setToolTip(QtGui.QApplication.translate("dsvxtb", "How many times to repeat. Use 0 to see the list", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Repeat_NTimes.setText(QtGui.QApplication.translate("dsvxtb", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dsvxtb", "Command recorder", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Input.setToolTip(QtGui.QApplication.translate("dsvxtb", "Print register next to the Base register", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Input.setText(QtGui.QApplication.translate("dsvxtb", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Pulse.setText(QtGui.QApplication.translate("dsvxtb", "Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command.setText(QtGui.QApplication.translate("dsvxtb", "Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Clear.setText(QtGui.QApplication.translate("dsvxtb", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Txt.setToolTip(QtGui.QApplication.translate("dsvxtb", "Enter command line here, for help - enter help. \n"
"Useful debugging commands:\n"
"w0 #: pulse bits in CSR\n"
"w1 #: set bits in CSR\n"
"w2 #: clear bits in CSR\n"
"r64: read Status\n"
"r128: read ChipSkop\n"
"r192: read Output FIFO\n"
"r/w320: read/write Sequencer\n"
"r/w384: read/write SPI\n"
"\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Command_Txt.setText(QtGui.QApplication.translate("dsvxtb", "h", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Read.setToolTip(QtGui.QApplication.translate("dsvxtb", "Read register, specified in Base", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Read.setText(QtGui.QApplication.translate("dsvxtb", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Set.setText(QtGui.QApplication.translate("dsvxtb", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Add.setText(QtGui.QApplication.translate("dsvxtb", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg_Value.setText(QtGui.QApplication.translate("dsvxtb", "0x00000000", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("dsvxtb", "Slave number on the APB bus", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dsvxtb", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Reg.setToolTip(QtGui.QApplication.translate("dsvxtb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Base register. <br />  0: CMDR. read/write. Command register, APB3_SBO_0 in the design</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> 64: STATR. read only. Status register. APB3_R32_0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">128: CHIPSKOP. ro. APB3_R32_1<br />192: OUTFIFO. ro. APB3_R32_2<br />256: TLK_RXD. ro. APB3_R32_3</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Dbg_Verbosity.setText(QtGui.QApplication.translate("dsvxtb", "Verbosity", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Chipskop_Arm.setToolTip(QtGui.QApplication.translate("dsvxtb", "Arm Chipskop. It will run until trigger comes", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Chipskop_Arm.setText(QtGui.QApplication.translate("dsvxtb", "Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Chipskop.setToolTip(QtGui.QApplication.translate("dsvxtb", "Send the Chipskop data, Chipskop is an internal logic analizer.", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Chipskop.setText(QtGui.QApplication.translate("dsvxtb", "Chipskop", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Chipskop_Trig.setToolTip(QtGui.QApplication.translate("dsvxtb", "Trigger the Chipskop. The chipskop data are ready for viewing", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_Chipskop_Trig.setText(QtGui.QApplication.translate("dsvxtb", "Trig", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Dbg_Verbosity_Txt.setToolTip(QtGui.QApplication.translate("dsvxtb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x00 - quiet</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x01 - errors</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x02 - warnings</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x04 - info</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x08 - detailed info</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x10 - very detailed info</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x20 - debuging info</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x40 - super detailed info</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x100 - disable check</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x200 - jumper instead of SRC</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">0x400 - disable event sending</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Dbg_Verbosity_Txt.setText(QtGui.QApplication.translate("dsvxtb", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_EFROM.setToolTip(QtGui.QApplication.translate("dsvxtb", "Print content of Flash ROM memory.", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Run_EFROM.setText(QtGui.QApplication.translate("dsvxtb", "EFROM", None, QtGui.QApplication.UnicodeUTF8))
        self.my_CTest.setToolTip(QtGui.QApplication.translate("dsvxtb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Test of the serial control protocol (\'t0\').<br />The commands are sent over SO line and it is checked for proper bit settng in the command register.  </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.my_CTest.setText(QtGui.QApplication.translate("dsvxtb", "CTest", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dsvxtb", "Registers manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Help.setText(QtGui.QApplication.translate("dsvxtb", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Reset.setToolTip(QtGui.QApplication.translate("dsvxtb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Test of the serial control protocol (\'t\').<br />The commands are sent over SO line and it is checked for proper bit settng in the command register.  </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.my_Reset.setText(QtGui.QApplication.translate("dsvxtb", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DumpFIFO.setToolTip(QtGui.QApplication.translate("dsvxtb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Test of the serial control protocol (\'t\').<br />The commands are sent over SO line and it is checked for proper bit settng in the command register.  </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.my_DumpFIFO.setText(QtGui.QApplication.translate("dsvxtb", "FIFO", None, QtGui.QApplication.UnicodeUTF8))
        self.my_STest.setToolTip(QtGui.QApplication.translate("dsvxtb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Test of the serial control protocol with sequenser (\'t1\').<br />  </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.my_STest.setText(QtGui.QApplication.translate("dsvxtb", "STest", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Debug), QtGui.QApplication.translate("dsvxtb", "Debug", None, QtGui.QApplication.UnicodeUTF8))

